# Lab 7: Contextual Bag of Words with Pytorch
### COSC 426: Fall 2025, Colgate University

Use this notebook to answer the questions in `Lab7.md`. Make sure to include in this notebook all the tests and experiments you run. Make sure to also cite any external resources you use. 

## Part 1: Familiarize yourself with the different components of the CBOW model

Add as many code chunks and markdown chunks as required to answer the questions in this part.

In [34]:
import CBOW
import torch

### Part 1.1


In [35]:
data4 = CBOW.CBOW_Dataset("./data/sample-alice.txt", "./data/sample_vocab.txt", 4)

In [ ]:
print(f"Num training examples: {len(data4.X)}")

Num training examples: 336


In [39]:
data4.X

[tensor([  0,   0,   0,   0, 142, 134,  17, 133]),
 tensor([  0,   0,   0, 150, 134,  17, 133, 116]),
 tensor([  0,   0, 150, 142,  17, 133, 116,  60]),
 tensor([  0, 150, 142, 134, 133, 116,  60,   7]),
 tensor([150, 142, 134,  17, 116,  60,   7,  26]),
 tensor([142, 134,  17, 133,  60,   7,  26, 145]),
 tensor([134,  17, 133, 116,   7,  26, 145,  18]),
 tensor([ 17, 133, 116,  60,  26, 145,  18, 128]),
 tensor([133, 116,  60,   7, 145,  18, 128, 120]),
 tensor([116,  60,   7,  26,  18, 128, 120,  95]),
 tensor([ 60,   7,  26, 145, 128, 120,  95, 139]),
 tensor([  7,  26, 145,  18, 120,  95, 139, 150]),
 tensor([ 26, 145,  18, 128,  95, 139, 150,   0]),
 tensor([145,  18, 128, 120, 139, 150,   0,   0]),
 tensor([ 18, 128, 120,  95, 150,   0,   0,   0]),
 tensor([128, 120,  95, 139,   0,   0,   0,   0]),
 tensor([  0,   0,   0,   0,  15,  64, 113,  26]),
 tensor([  0,   0,   0, 150,  64, 113,  26,  88]),
 tensor([  0,   0, 150,  15, 113,  26,  88, 100]),
 tensor([  0, 150,  15,  64,  2

In [37]:
data2 = CBOW.CBOW_Dataset("./data/sample-alice.txt", "./data/sample_vocab.txt", 2)

In [38]:
print(f"Num training examples: {len(data2.X)}")

Num training examples: 336


Since we are using padding, both of the training sets have the same number of examples, which is the number of words in the text.

A training example looks like an embedding, of widow size*2. We want to use a *2 since we want to account for every word, hence we need to add padding so that the window accounts for every word. We frist divide the text into sentences, and further divide the sentences into tokens. Tokens are then converted into integer values using the vocab:id mapping. We chunk these values into pairs in the format of n words:n+1th word, where n is the window size. 

The final dataset is not case sensitive. To make it case sensitive, we can remove `.lower()` funciton in the preprocessing, and treat capitalized words as diffrent tokens. 

### Part 1.2


Conceptually, the torch.nn.Embedding layer is weights that convert input into output, and the number of weights we have is the size of the input * the size of the output. The dimensions of the input is the size of the vocab and the output is nEmbed. This makes sense becuase we want the embedding to be denser then the vocabasize.

Conceptually, the linear layer is the weights that convert the output vecotr of the Embedding layer to the vector representation of a word. 
The input dimension is the same as `nEmbed` and the output dimension is the vocabsize. 
This makes sense because in the end we want the result to be in the size of the vocab. 

3.The `foward` function multiplies the embedding weights to the input and calcualtes the average.

4. The `loss` fucntion calculates the crossenthropy loss. 

### Part 1.3


num_epochs: how many times we want to repeat the training process.
lr: the amount change we want to make in each epoch
batch_size: the amount of data we want to pass at each forward. 
train_data: the data we use to train the model
val_data: the data we use to minimize the loss
device: the device we want to use(cpu, cuda etc.)

train_data: dataset from which to load the data.
batch_size: how many samples per batch to load
shuffle: set to True to have the data reshuffled at every epoch (default: False).

It returns an iterable list of batches.

1.3 
The first line is moving the data from CPU to the device.
The second line computes the CrossEntropyLoss loss.
3: Clearing the gradient for the next update. 
4: Adjusts the weight to optimize the model(to minimize the loss of the model). Calculating the gradient. 
5: Updating the weights

In [ ]:
model = CBOW.CBOW_Trainer()

SyntaxError: invalid syntax (1369116857.py, line 1)

### Part 1.4


## Part 2: Train and evaluate a CBOW model on toy data, and explore the word embeddings

Add as many code chunks and markdown chunks as required to answer the questions in this part.


In [ ]:
## Function to get device


def get_device(args):
    use_cuda = not args["cuda"] and torch.cuda.is_available()
    use_mps = not args["mps"] and torch.backends.mps.is_available()

    if use_cuda:
        device = torch.device("cuda")
    elif use_mps:
        device = torch.device("mps")
    else:
        device = torch.device("cpu")

    return device

### Initialize model and datasets

### Evaluate randomly initialized model

* Report loss and accuracy on the training data
* Report cosine similarity between the 4 word pairs

### Train the model

### Evaluate trained model

* Report loss and accuracy on the training data
* Report cosine similarity between the 4 word pairs

### Discussion and reflection

* Do you think that the model has learned the task? Do you think the model has learned useful embeddings?

* Does it make sense to use embedding size of 300 for this toy data? Why or why not? 

## Part 3: Explore the role of training data on the word embeddings that are learned

### Train models

Answer question 1 here

### Come up with list of words
Answer questions 2 and 3 here

### Test your hypotheses

Answer question 4 here


## Part 4 (Optional): Explore the role of other factors on the word embeddings that are learned